FROM node:latest

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build Next.js
RUN npm run build

# Expost frontend port
EXPOSE 3000

# Start application
CMD [ "npm", "start" ]